**Trabalhando com diferentes tipos de arquivos**

**Arquivos JSON**

In [6]:
import pandas as pd

In [9]:
import json

In [12]:
dados_pacientes = pd.read_json('/content/pacientes.json')

In [13]:
dados_pacientes

,ID_paciente,Doenca_cardiaca,IMC,Fumante,Consumo_alcool,AVC,Saude_fisica,Saude_mental,Dificuldade_caminhar,Sexo_biologico,Faixa_etaria,Raca,Diabetes,Atividade_fisica,Saude_geral,Horas_sono,Asma,Doenca_renal,Cancer_pele
0,0,Nao,16.60,Sim,Nao,Nao,3,30,Nao,Feminino,55-59,Branca,Sim,Sim,Muito boa,5,Sim,Nao,Sim
1,1,Nao,20.34,Nao,Nao,Sim,0,0,Nao,Feminino,80 ou +,Branca,Nao,Sim,Muito boa,7,Nao,Nao,Nao
2,2,Nao,26.58,Sim,Nao,Nao,20,30,Nao,Masculino,65-69,Branca,Sim,Sim,Razoavel,8,Sim,Nao,Nao
3,3,Nao,24.21,Nao,Nao,Nao,0,0,Nao,Feminino,75-79,Branca,Nao,No,Boa,6,Nao,Nao,Sim
4,4,Nao,23.71,Nao,Nao,Nao,28,0,Sim,Feminino,40-44,Branca,Nao,Sim,Muito boa,8,Nao,Nao,Nao
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,Nao,28.29,Sim,Nao,Nao,10,20,Nao,Feminino,65-69,Preta,Sim,Sim,Razoavel,8,Nao,Nao,Nao
996,996,Nao,25.69,Sim,Nao,Nao,0,0,Nao,Feminino,75-79,Branca,Nao,Sim,Excelente,8,Nao,Nao,Nao
997,997,Sim,26.99,Nao,Nao,Nao,1,0,Nao,Masculino,70-74,Branca,Nao,Sim,Muito boa,8,Nao,Nao,Nao
998,998,Nao,44.29,Nao,Nao,Nao,30,0,Sim,Feminino,70-74,Branca,Sim,No,Boa,6,Sim,Nao,Nao
999,999,Nao,25.83,Nao,Nao,Nao,0,0,Nao,Masculino,70-74,Preta,Sim,No,Excelente,7,Nao,Nao,Nao

In [14]:
dados_pacientes2 = pd.read_json('/content/pacientes_2.json')
dados_pacientes2

,Pesquisa,Ano,Pacientes
0,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_bi..."
1,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '02', 'Faixa_etaria': '80 ou +', 'Sexo_..."
2,Principais Indicadores de Doenca Cardiaca,2020,"{'ID': '03', 'Faixa_etaria': '65-69', 'Sexo_bi..."

In [16]:
df_norm = pd.json_normalize(dados_pacientes2['Pacientes'])

In [17]:
df_norm

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"

In [18]:
df_norm.to_json('historico_pac_norm.json')

In [19]:
pd.read_json('historico_pac_norm.json')

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude
0,1,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]"
1,2,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC]
2,3,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]"